# 录播姬(rectpye)
RECHEME:
  # (可选)全局 是否启用录播姬认证。如果没有该选项，就默认为 false
  # 默认为 false
  RECHEME_BASIC: false
  # (可选)全局 录播姬认证账号密码。如果没有该选项，就默认为 空
  # 默认为 空
  RECHEME_BASIC_USER: "admin"
  RECHEME_BASIC_PASS: "admin"

  # 名称，没有限制
  Z9001:
    # 录播姬地址
    - URL: http://10.0.0.101:9001
  Z9002:
    - URL: http://10.0.0.101:9002
  Z9003:
    - URL: http://10.0.0.101:9003
  Z9004:
    - URL: http://10.0.0.101:9004
  Z9005:
    - URL: http://10.0.0.101:9005
  Z9006:
    - URL: http://10.0.0.101:9006
  Z9007:
    - URL: http://10.0.0.101:9007
  Z9010:
    - URL: http://10.0.0.101:9010
  Z9041:
    - URL: http://10.0.0.101:9041
  Z9042:
    - URL: http://10.0.0.101:9042
  Z9051:
    - URL: http://10.0.0.101:9051
  Z9052:
    - URL: http://10.0.0.101:9052
  Z9090:
    - URL: http://10.0.0.101:9090
  Z9091:
    - URL: http://10.0.0.101:9091
  Z9098:
    - URL: http://10.0.0.101:9098
  Z9099:
    - URL: http://10.0.0.101:9099


# BLREC(rectpye)
BLREC:
  # (可选)BLREC全局设置 是否启用BLREC认证。如果没有该选项，就默认为 true
  # 默认为 true
  BLREC_BASIC: true
  # (可选)BLREC全局设置 BLREC认证账号密码。如果没有该选项，就默认为 bili2233
  # 默认为 bili2233
  BLREC_BASIC_KEY: "88888888"

  # 名称，没有限制
  Z9101:
    - URL: http://10.0.0.101:9101
  Z9102:
    - URL: http://10.0.0.101:9102
  Z9198:
    - URL: http://10.0.0.101:9198
  Z9199:
    - URL: http://10.0.0.101:9199